setlocal EnableDelayedExpansion

SET FROMDIRECTORY=path
SET TODIRECTORY=path
SET FILENAME=\file
SET EXT=.txt

SET LOG=LOG_CopyFileFromServer.log

SET USER=User123
SET PASSWORD=Pass123

ECHO *------------------------------* >> %LOG%
ECHO *          FILE TO COPY        * >> %LOG%
ECHO *------------------------------* >> %LOG%

NET USE %FROMDIRECTORY% %PASSWORD% /USER:%USER%
IF %ERRORLEVEL% NEQ 0 ( GOTO ERRORCONNECTION ) 
ECHO SUCCESSFUL CONNECTION >> %LOG%

ECHO * FILE TO COPY: %FROMDIRECTORY%%FILENAME%%EXT% >> %LOG%

IF EXIST %FROMDIRECTORY%%FILENAME%%EXT% (
    COPY %FROMDIRECTORY%%FILENAME%%EXT% %TODIRECTORY%%FILENAME%%EXT% >> %LOG%
) ELSE ( ECHO FILE NOT FOUND %FILENAME% >> %LOG% )

GOTO EXIT

:ERRORCONNECTION
    ECHO FAIL CONNECTION >> %LOG%

:EXIT
    ECHO TO DIRECTORY : %TODIRECTORY% >> %LOG%
    NET USE %FROMDIRECTORY%  /DELETE /Y
    ECHO.